package com.toy.anagrams.ui;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author josmel torres
 */
public class PlantillaFuncional extends javax.swing.JFrame {

    /**
     * Creates new form PlantillaFuncional
     */
    public PlantillaFuncional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        OlvidarContraseña = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JTextField();
        Registrar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        BotonRegistro = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        Logo = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Titulo");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 50));

        Email.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("E-mail o usuario");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 252, 10));

        OlvidarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        OlvidarContraseña.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        OlvidarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        OlvidarContraseña.setText("Olvidaste tu contraseña");
        OlvidarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OlvidarContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OlvidarContraseñaMouseExited(evt);
            }
        });
        getContentPane().add(OlvidarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        TextoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TextoUsuario.setBorder(null);
        TextoUsuario.setOpaque(false);
        getContentPane().add(TextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 250, 20));

        Registrar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText("Crear nueva cuenta");
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarMouseExited(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 252, 10));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Recordar mis datos");
        jCheckBox1.setOpaque(false);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 150, 20));

        BotonRegistro.setBackground(new java.awt.Color(0, 0, 0));
        BotonRegistro.setForeground(new java.awt.Color(255, 255, 0));
        BotonRegistro.setText("Ingresar");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 250, 20));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaz 2/logo (2).jpg"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 100, 80));

        ImagenFondo.setForeground(new java.awt.Color(255, 255, 51));
        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaz 2/negro.jpg"))); // NOI18N
        ImagenFondo.setText("jLabel1");
        ImagenFondo.setOpaque(true);
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OlvidarContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvidarContraseñaMouseEntered
        OlvidarContraseña.setForeground(Color.gray);
    }//GEN-LAST:event_OlvidarContraseñaMouseEntered

    private void OlvidarContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvidarContraseñaMouseExited
        OlvidarContraseña.setForeground(Color.black);
    }//GEN-LAST:event_OlvidarContraseñaMouseExited

    private void RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseEntered
        OlvidarContraseña.setForeground(Color.gray);
    }//GEN-LAST:event_RegistrarMouseEntered

    private void RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseExited
        OlvidarContraseña.setForeground(Color.black);
    }//GEN-LAST:event_RegistrarMouseExited

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
bienvenida siguiente = new bienvenida();
siguiente.setVisible(true);
this.dispose();
    }//GEN-LAST:event_BotonRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantillaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantillaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantillaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantillaFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PlantillaFuncional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel OlvidarContraseña;
    private javax.swing.JLabel Registrar;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
