/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toy.anagrams.ui;



/**
 *
 * @author josmel torres
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public RecuperarContraseña() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRegistro1 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TextoRecuperacion = new javax.swing.JLabel();
        TextoRecuperacion1 = new javax.swing.JLabel();
        CampoCorreo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        BotonRegistro = new javax.swing.JButton();
        BotonRegistro2 = new javax.swing.JButton();
        ImagenFondo = new javax.swing.JLabel();

        BotonRegistro1.setBackground(new java.awt.Color(0, 0, 0));
        BotonRegistro1.setForeground(new java.awt.Color(255, 255, 0));
        BotonRegistro1.setText("Registrarse ");
        BotonRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistro1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Recuperar contraseña");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, 50));

        TextoRecuperacion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TextoRecuperacion.setForeground(new java.awt.Color(255, 255, 255));
        TextoRecuperacion.setText("Ingresa tu correo electrónico o usuario");
        getContentPane().add(TextoRecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 40));

        TextoRecuperacion1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TextoRecuperacion1.setForeground(new java.awt.Color(255, 255, 255));
        TextoRecuperacion1.setText("para buscar tu cuenta.");
        getContentPane().add(TextoRecuperacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 210, 40));

        CampoCorreo.setForeground(new java.awt.Color(255, 255, 255));
        CampoCorreo.setBorder(null);
        getContentPane().add(CampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, 20));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 252, 10));

        BotonRegistro.setBackground(new java.awt.Color(0, 0, 0));
        BotonRegistro.setForeground(new java.awt.Color(255, 255, 0));
        BotonRegistro.setText("Buscar");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, 20));

        BotonRegistro2.setBackground(new java.awt.Color(0, 0, 0));
        BotonRegistro2.setForeground(new java.awt.Color(255, 255, 0));
        BotonRegistro2.setText("Cancelar");
        BotonRegistro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistro2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, 20));

        ImagenFondo.setForeground(new java.awt.Color(255, 255, 51));
        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaz 2/negro.jpg"))); // NOI18N
        ImagenFondo.setText("jLabel1");
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void BotonRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistro1ActionPerformed

    private void BotonRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistro2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton BotonRegistro1;
    private javax.swing.JButton BotonRegistro2;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel TextoRecuperacion;
    private javax.swing.JLabel TextoRecuperacion1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
