/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toy.anagrams.ui;

/**
 *
 * @author josmel torres
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Nombre4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        SexoHombre = new javax.swing.JRadioButton();
        Sexo = new javax.swing.JLabel();
        Sex = new javax.swing.JRadioButton();
        Contraseña = new javax.swing.JLabel();
        SexoMujer = new javax.swing.JRadioButton();
        CampoApellido = new javax.swing.JTextField();
        CampoNombre = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        BotonRegistro = new javax.swing.JButton();
        Fecha1 = new javax.swing.JTextField();
        Fecha = new javax.swing.JPasswordField();
        SeparadorFecha = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Registro");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 50));

        Nombre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 51));
        Nombre.setText("Apellido");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 80, 30));

        Nombre1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(255, 51, 51));
        Nombre1.setText("Número de celular o correo electrónico");
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, 30));

        Nombre2.setBackground(new java.awt.Color(255, 255, 255));
        Nombre2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2.setText("Fecha de nacimiento");
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 30));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, 10));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 10));

        Nombre4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        Nombre4.setForeground(new java.awt.Color(255, 255, 51));
        Nombre4.setText("nombre");
        getContentPane().add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 30));

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 10));

        SexoHombre.setForeground(new java.awt.Color(255, 255, 255));
        SexoHombre.setText("Hombre");
        SexoHombre.setOpaque(false);
        getContentPane().add(SexoHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Sexo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        Sexo.setForeground(new java.awt.Color(255, 255, 255));
        Sexo.setText("Sexo\n");
        getContentPane().add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 110, 30));

        Sex.setForeground(new java.awt.Color(255, 255, 255));
        Sex.setText("Prefiero no decirlo");
        Sex.setOpaque(false);
        getContentPane().add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        Contraseña.setBackground(new java.awt.Color(255, 255, 255));
        Contraseña.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(153, 255, 102));
        Contraseña.setText("Contraseña");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 30));

        SexoMujer.setForeground(new java.awt.Color(255, 255, 255));
        SexoMujer.setText("Mujer");
        SexoMujer.setOpaque(false);
        getContentPane().add(SexoMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        CampoApellido.setForeground(new java.awt.Color(255, 255, 255));
        CampoApellido.setBorder(null);
        CampoApellido.setOpaque(false);
        CampoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, 20));

        CampoNombre.setForeground(new java.awt.Color(255, 255, 255));
        CampoNombre.setBorder(null);
        CampoNombre.setOpaque(false);
        CampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 20));

        CampoCorreo.setForeground(new java.awt.Color(255, 255, 255));
        CampoCorreo.setBorder(null);
        CampoCorreo.setOpaque(false);
        getContentPane().add(CampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, 20));

        BotonRegistro.setBackground(new java.awt.Color(0, 0, 0));
        BotonRegistro.setForeground(new java.awt.Color(255, 255, 0));
        BotonRegistro.setText("Registrarse ");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, -1));

        Fecha1.setForeground(new java.awt.Color(255, 255, 255));
        Fecha1.setBorder(null);
        Fecha1.setOpaque(false);
        Fecha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fecha1KeyTyped(evt);
            }
        });
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 20));

        Fecha.setForeground(new java.awt.Color(240, 240, 240));
        Fecha.setBorder(null);
        Fecha.setOpaque(false);
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 20));

        SeparadorFecha.setBackground(new java.awt.Color(51, 51, 51));
        SeparadorFecha.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(SeparadorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 10));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(153, 255, 102));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 10));

        ImagenFondo.setForeground(new java.awt.Color(255, 255, 51));
        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaz 2/negro.jpg"))); // NOI18N
        ImagenFondo.setText("jLabel1");
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreActionPerformed
        String input = CampoNombre.getText();
    if (!input.matches("[a-zA-Z]*")) {
        // Si la entrada contiene caracteres no alfabéticos, elimina esos caracteres
        input = input.replaceAll("[^a-zA-Z]", "");
        CampoNombre.setText(input);
    }
    }//GEN-LAST:event_CampoNombreActionPerformed

    private void CampoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoApellidoActionPerformed
               

    }//GEN-LAST:event_CampoApellidoActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
  PlantillaFuncional ventana = new PlantillaFuncional();
  ventana.setVisible(true);
  this.dispose();
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void Fecha1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fecha1KeyTyped
       String input = Fecha1.getText();
    if (!input.matches("[0-9]*")) {
        // Si la entrada no es un número, elimina los caracteres no válidos
        input = input.replaceAll("[^0-9]", "");
        Fecha1.setText(input);
    }
    }//GEN-LAST:event_Fecha1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JTextField CampoApellido;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPasswordField Fecha;
    private javax.swing.JTextField Fecha1;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre4;
    private javax.swing.JSeparator SeparadorFecha;
    private javax.swing.JRadioButton Sex;
    private javax.swing.JLabel Sexo;
    private javax.swing.JRadioButton SexoHombre;
    private javax.swing.JRadioButton SexoMujer;
    private javax.swing.JLabel Titulo;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
